# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_quickdoxy(object):
    def setupUi(self, quickdoxy):
        quickdoxy.setObjectName("quickdoxy")
        quickdoxy.resize(603, 246)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon_main"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        quickdoxy.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(quickdoxy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.paramTree = parameterWidget(self.centralWidget)
        self.paramTree.setHeaderHidden(True)
        self.paramTree.setObjectName("paramTree")
        self.paramTree.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.paramTree)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.runbutton = QtWidgets.QPushButton(self.centralWidget)
        self.runbutton.setObjectName("runbutton")
        self.horizontalLayout.addWidget(self.runbutton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        quickdoxy.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(quickdoxy)
        self.statusBar.setObjectName("statusBar")
        quickdoxy.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(quickdoxy)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 603, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTool = QtWidgets.QMenu(self.menuBar)
        self.menuTool.setObjectName("menuTool")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        quickdoxy.setMenuBar(self.menuBar)
        self.actionDoc = QtWidgets.QAction(quickdoxy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/docu"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDoc.setIcon(icon1)
        self.actionDoc.setObjectName("actionDoc")
        self.actionAbout = QtWidgets.QAction(quickdoxy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/info"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon2)
        self.actionAbout.setObjectName("actionAbout")
        self.actionToggle_log = QtWidgets.QAction(quickdoxy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/log"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionToggle_log.setIcon(icon3)
        self.actionToggle_log.setObjectName("actionToggle_log")
        self.actionRunDoxygen = QtWidgets.QAction(quickdoxy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/run"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRunDoxygen.setIcon(icon4)
        self.actionRunDoxygen.setObjectName("actionRunDoxygen")
        self.menuHelp.addAction(self.actionDoc)
        self.menuHelp.addAction(self.actionAbout)
        self.menuTool.addAction(self.actionToggle_log)
        self.menuFile.addAction(self.actionRunDoxygen)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTool.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(quickdoxy)
        QtCore.QMetaObject.connectSlotsByName(quickdoxy)

    def retranslateUi(self, quickdoxy):
        _translate = QtCore.QCoreApplication.translate
        quickdoxy.setWindowTitle(_translate("quickdoxy", "quickdoxy"))
        self.runbutton.setText(_translate("quickdoxy", "Run doxygen"))
        self.menuHelp.setTitle(_translate("quickdoxy", "Help"))
        self.menuTool.setTitle(_translate("quickdoxy", "Tools"))
        self.menuFile.setTitle(_translate("quickdoxy", "File"))
        self.actionDoc.setText(_translate("quickdoxy", "Documentation"))
        self.actionDoc.setToolTip(_translate("quickdoxy", "opens the documentation"))
        self.actionDoc.setShortcut(_translate("quickdoxy", "F1"))
        self.actionAbout.setText(_translate("quickdoxy", "About"))
        self.actionAbout.setToolTip(_translate("quickdoxy", "displays version information"))
        self.actionAbout.setShortcut(_translate("quickdoxy", "Shift+F1"))
        self.actionToggle_log.setText(_translate("quickdoxy", "toggle log"))
        self.actionToggle_log.setToolTip(_translate("quickdoxy", "opens / closes the log window"))
        self.actionToggle_log.setShortcut(_translate("quickdoxy", "Ctrl+L"))
        self.actionRunDoxygen.setText(_translate("quickdoxy", "Run Doxygen"))
        self.actionRunDoxygen.setToolTip(_translate("quickdoxy", "Runs doxygen with the specified parameters"))
        self.actionRunDoxygen.setShortcut(_translate("quickdoxy", "F2"))

from frontend_subclasses import parameterWidget
import frontendRC
